version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: "@types/classnames"
    versions:
    - 2.2.11
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.3
    - 5.2.0
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.9
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: "@babel/plugin-proposal-decorators"
    versions:
    - 7.12.12
    - 7.12.13
    - 7.13.5
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.12.1
    - 7.12.13
    - 7.13.0
  - dependency-name: "@babel/plugin-proposal-json-strings"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.4
    - 11.2.5
  - dependency-name: "@babel/plugin-proposal-logical-assignment-operators"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: "@babel/plugin-proposal-nullish-coalescing-operator"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: "@babel/plugin-transform-object-assign"
    versions:
    - 7.12.1
  - dependency-name: "@babel/plugin-proposal-pipeline-operator"
    versions:
    - 7.12.1
  - dependency-name: "@babel/plugin-proposal-function-bind"
    versions:
    - 7.12.1
  - dependency-name: "@babel/plugin-proposal-export-namespace-from"
    versions:
    - 7.12.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
