export const theme = {
  button: {
    variants: {
      default: {
        states: {
          disabled: {
            container: [
              'font-manrope',
              'font-medium',
              'rounded-button',
              'bg-button-disabled',
              'text-button-primary',
              'px-6',
              'py-1',
              'min-w-min',
              'dark:bg-gray-800',
              'dark:text-button-disabled',
              'focus:outline-none',
              'cursor-not-allowed',
            ],
          },
        },
        components: {
          container: [
            'font-manrope',
            'font-medium',
            'rounded-md',
            'bg-green-600',
            'text-button-primary',
            'px-6',
            'py-1',
            'min-w-min',
            'dark:bg-gray-800',
            'dark:text-button-primary',
            'hover:bg-green-700',
            'focus:outline-none',
            'mr-1',
            'active:bg-green-500',
          ],
        },
      },
      secondary: {
        container: [
          'font-manrope',
          'font-medium',
          'text-bold',
          'rounded-button',
          'bg-button-outlined',
          'text-button-outlined',
          'px-6',
          'py-1',
          'min-w-min',
          'dark:bg-gray-800',
          'dark:text-button-primary',
          'border-2',
          'border-button-outlined',
          'hover:bg-button-outlined-hover',
          'hover:text-button-primary',
          'focus:outline-none',
          'active:bg-button-pressed',
        ],
      },
    },
  },
};
