import { ThemeType } from '../types';

export const preset: ThemeType = {
  button: {
    states: {
      disabled: {
        primary: {
          container: [
            'font-manrope',
            'font-medium',
            'rounded-button',
            'bg-button-disabled',
            'text-button-primary',
            'px-6',
            'py-1',
            'min-w-min',
            'dark:bg-gray-800',
            'dark:text-button-disabled',
            'focus:outline-none',
            'cursor-not-allowed',
          ],
        },
        secondary: {
          container: [
            'font-manrope',
            'font-medium',
            'text-bold',
            'text-button-outlined-disabled',
            'rounded-button',
            'px-6',
            'py-1',
            'min-w-min',
            'dark:bg-gray-800',
            'dark:text-button-primary',
            'border-2',
            'border-button-outlined-disabled',
            'hover:bg-button-outlined-hover',
            'hover:text-button-primary',
            'focus:outline-none',
            'active:bg-button-pressed',
          ],
        },
      },
    },
    variants: {
      primary: {
        container: [
          'font-manrope',
          'font-medium',
          'rounded-button',
          'bg-button-primary',
          'text-button-primary',
          'px-6',
          'py-1',
          'min-w-min',
          'dark:bg-gray-800',
          'dark:text-button-primary',
          'hover:bg-button-hover',
          'focus:outline-none',
          'mr-1',
          'active:bg-button-pressed',
        ],
      },
      secondary: {
        container: [
          'font-manrope',
          'font-medium',
          'text-bold',
          'rounded-button',
          'bg-button-outlined',
          'text-button-outlined',
          'px-6',
          'py-1',
          'min-w-min',
          'dark:bg-gray-800',
          'dark:text-button-primary',
          'border-2',
          'border-button-outlined',
          'hover:bg-button-outlined-hover',
          'hover:text-button-primary',
          'focus:outline-none',
          'active:bg-button-pressed',
        ],
      },
    },
  },
};
