// Note: this should be move out to the Button stories folder

export const outlinedVariants = {
  outlined: {
    primary: `
      font-manrope
      font-medium
      text-bold
      rounded-button
      bg-button-outlined
      text-button-outlined
      px-6
      py-1
      min-w-min
      dark:bg-gray-800
      dark:text-button-primary
      border-2
      border-button-outlined
      hover:bg-button-outlined-hover
      hover:text-button-primary
      focus:outline-none
      active:bg-button-pressed
    `,
    disabled: `
      font-manrope
      font-medium  
      text-bold
      text-button-outlined-disabled
      rounded-button
      px-6
      py-1
      min-w-min 
      dark:bg-gray-800
      dark:text-button-primary
      border-2
      border-button-outlined-disabled
      hover:bg-button-outlined-hover
      hover:text-button-primary
      focus:outline-none
      active:bg-button-pressed
    `,
    small: `
      font-manrope
      font-medium  
      text-bold
      bg-button-outlined 
      text-button-outlined 
      rounded-button 
      bg-button-primary 
      text-button-primary 
      px-5 
      py-1 
      min-w-min
      border-2
      border-button-outlined
      hover:bg-button-outlined-hover
      hover:text-button-primary  
      dark:bg-gray-800
      dark:text-button-primary
      focus:outline-none 
      active:bg-button-pressed
      text-sm
    `,
    medium: `
      font-manrope
      font-medium  
      text-bold
      bg-button-outlined 
      text-button-outlined 
      rounded-button 
      bg-button-primary 
      text-button-primary 
      px-6 
      py-1 
      min-w-min 
      border-2
      border-button-outlined
      hover:bg-button-outlined-hover
      hover:text-button-primary  
      dark:bg-gray-800
      dark:text-button-primary
      focus:outline-none 
      active:bg-button-pressed
      text-md
    `,
    large: `
      font-manrope
      font-medium  
      text-bold
      bg-button-outlined 
      text-button-outlined 
      rounded-button 
      bg-button-primary 
      text-button-primary 
      px-6 
      py-1 
      min-w-min
      border-2
      border-button-outlined
      hover:bg-button-outlined-hover
      hover:text-button-primary  
      dark:bg-gray-800
      dark:text-button-primary
      focus:outline-none 
      active:bg-button-pressed
      text-lg
      `,
    stretched: `
      font-manrope
      font-medium
      text-bold
      bg-button-outlined
      text-button-outlined
      rounded-button
      bg-button-primary
      text-button-primary
      px-6
      py-1
      w-full
      border-2
      border-button-outlined
      hover:bg-button-outlined-hover
      hover:text-button-primary
      dark:bg-gray-800
      dark:text-button-primary
      focus:outline-none
      active:bg-button-pressed
      text-md
    `,
    icon: {
      left: `
      font-manrope
      font-medium
      text-bold
      rounded-button
      bg-button-outlined
      text-button-outlined
      px-6
      py-1
      min-w-min
      dark:bg-gray-800
      dark:text-button-primary
      border-2
      border-button-outlined
      hover:bg-button-outlined-hover
      hover:text-button-primary
      focus:outline-none
      active:bg-button-pressed
    `,
      right: `
      font-manrope
      font-medium
      text-bold
      rounded-button
      bg-button-outlined
      text-button-outlined
      px-6
      py-1
      min-w-min
      dark:bg-gray-800
      dark:text-button-primary
      border-2
      border-button-outlined
      hover:bg-button-outlined-hover
      hover:text-button-primary
      focus:outline-none
      active:bg-button-pressed    
    `,
    },
  },
};
