export const button = {
  variants: {
    default: {
      container: [
        'font-manrope',
        'font-medium',
        'rounded-button',
        'bg-button-primary',
        'text-button-primary',
        'px-6',
        'py-1',
        'min-w-min',
        'dark:bg-gray-800',
        'dark:text-button-primary',
        'hover:bg-button-hover',
        'focus:outline-none',
        'active:bg-button-pressed',
        'disabled:text-button-primary',
        'disabled:bg-button-disabled',
        'disabled:cursor-not-allowed',
        'disabled:border-button-disabled',
      ],
      skeleton: {
        container: ['bg-gray-400', 'rounded-button', 'w-28', 'h-8'],
      },
    },
    secondary: {
      container: [
        'font-manrope',
        'font-medium',
        'text-bold',
        'rounded-button',
        'bg-button-outlined',
        'text-button-outlined',
        'px-6',
        'py-1',
        'min-w-min',
        'dark:bg-gray-800',
        'dark:text-button-primary',
        'border-2',
        'border-button-outlined',
        'hover:bg-button-outlined-hover',
        'hover:text-button-primary',
        'focus:outline-none',
        'active:bg-button-pressed',
        'active:border-button-outlined-pressed',
        'disabled:text-button-outlined-disabled',
        'disabled:bg-transparent',
        'disabled:border-button-outlined-disabled',
        'disabled:cursor-not-allowed',
      ],
      skeleton: {
        container: ['bg-gray-400', 'rounded-button', 'w-28', 'h-8'],
      },
    },
  },
};
