declare const LINK = "LINK";
declare const IMAGE = "IMAGE";
declare const HANDLED = "handled";
declare const NOT_HANDLED = "not-handled";
declare const BLOCKQUOTE = "blockquote";
declare const UNSTYLED = "unstyled";
declare const IMMUTABLE = "IMMUTABLE";
declare const RIGHT = "right";
declare const LEFT = "left";
declare const DEFAULT_HEIGHT = "auto";
declare const MARGIN_IMAGE = 50;
declare const ATOMIC = "atomic";
declare const STYLE_AUTO = "auto";
declare const MARGINS: string[];
declare const BACKSPACE_COMMAND = "backspace";
declare const HORIZONTAL_RULE = "HORIZONTAL_RULE";
declare const HR = "HR";
declare const CAMERA_CHAR_CODE = "d83d";
declare const P_TAG = "p";
declare const BR_TAG = "br";
declare const ANCHOR_TAG = "a";
declare const INPUT_TAG = "input";
declare const FIGURE_TAG = "figure";
declare const EMPTY_TAG = "empty";
declare const CODE_BLOCK = "code-block";
declare const SUBMIT = "submit";
declare const HR_TAG = "<hr />";
export { LINK, HANDLED, NOT_HANDLED, BLOCKQUOTE, UNSTYLED, IMAGE, IMMUTABLE, DEFAULT_HEIGHT, LEFT, RIGHT, MARGIN_IMAGE, ATOMIC, STYLE_AUTO, MARGINS, BACKSPACE_COMMAND, HORIZONTAL_RULE, HR, CAMERA_CHAR_CODE, P_TAG, BR_TAG, ANCHOR_TAG, INPUT_TAG, FIGURE_TAG, EMPTY_TAG, CODE_BLOCK, SUBMIT, HR_TAG, };
