declare const LINK = "LINK";
declare const IMAGE = "IMAGE";
declare const HANDLED = "handled";
declare const NOT_HANDLED = "not-handled";
declare const BLOCKQUOTE = "blockquote";
declare const UNSTYLED = "unstyled";
declare const IMMUTABLE = "IMMUTABLE";
declare const RIGHT = "right";
declare const LEFT = "left";
declare const DEFAULT_HEIGHT = "auto";
declare const MARGIN_IMAGE = 50;
declare const ATOMIC = "atomic";
declare const STYLE_AUTO = "auto";
declare const MARGINS: string[];
declare const BACKSPACE_COMMAND = "backspace";
export { LINK, HANDLED, NOT_HANDLED, BLOCKQUOTE, UNSTYLED, IMAGE, IMMUTABLE, DEFAULT_HEIGHT, LEFT, RIGHT, MARGIN_IMAGE, ATOMIC, STYLE_AUTO, MARGINS, BACKSPACE_COMMAND };
