"use strict";
exports.__esModule = true;
var LINK = "LINK";
exports.LINK = LINK;
var IMAGE = "IMAGE";
exports.IMAGE = IMAGE;
var HANDLED = "handled";
exports.HANDLED = HANDLED;
var NOT_HANDLED = "not-handled";
exports.NOT_HANDLED = NOT_HANDLED;
var BLOCK_QUOTE = "blockquote";
exports.BLOCK_QUOTE = BLOCK_QUOTE;
var UNSTYLED = "unstyled";
exports.UNSTYLED = UNSTYLED;
var IMMUTABLE = "IMMUTABLE";
exports.IMMUTABLE = IMMUTABLE;
