name: CI
on:
  push:
    branches:
      - dev
      - release
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - LICENSE
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - LICENSE

jobs:
  test_lint:
    name: Test & lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node-version: [14.16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Yarn v2
        run: yarn set version berry

      - name: Install packages
        run: yarn install

      - name: Add bin to PATH
        run: echo "./node_modules/.bin" >> $GITHUB_PATH

      - name: Run lint
        run: yarn run lint

      - name: Run tests with coverage
        run: yarn run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/*
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

  pull_request_format:
    name: Pull request format
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node-version: [14.16.x]
    if: |
      github.event_name == 'pull_request' &&
      github.head_ref != 'master' &&
      github.base_ref != 'master' &&
      startsWith(github.head_ref, 'dependabot/') != true
    steps:
      # PR title needs to follow format:
      # [keyword](optional scope): [title] [JIRAID]
      # e.g. fix(payment): Corrected logging BZ2-1234
      - name: Validate pull request title
        run: |
          [[ '${{ github.event.pull_request.title }}' =~ ^(build|chore|ci|docs|feat|fix|improvement|perf|refactor|revert|style|test)(\(.+\))?\!?:\ .{10,}$ ]]
          echo 0

  publish_storybook:
    name: Publish Storybook
    needs: test_lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node-version: [14.16.x]
    if: |
      github.event_name == 'pull_request'
    # if: (contains(fromJson('["release", "master"]'), github.base_ref) &&
    #   github.event.pull_request.merged == true)

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Yarn v2
        run: yarn set version berry

      - name: Install packages
        run: yarn install

      - name: Build storybook
        run: yarn run build-storybook

      - name: Set GitHub user details
        run: |
          git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
          git config --global user.name ${{ secrets.GIT_USER_NAME }}

      # - name: Create prerelease version
      #   run: npx lerna version --conventional-commits --conventional-prerelease --no-commit-hooks --create-release github --yes
      #   if: github.head_ref == 'release'

      # - name: Publish packages to npm as alpha
      #   run: npx lerna publish from-git --dist-tag alpha --yes
      #   if: github.head_ref == 'release'

      # - name: Create release version
      #   run: npx lerna version --conventional-commits --conventional-graduate --no-commit-hooks --create-release github --yes
      #   if: github.head_ref == 'master'

      # - name: Publish packages to npm
      #   run: npx lerna publish from-git --yes
      #   if: github.head_ref == 'master'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Sync files to AWS S3
        run: aws s3 sync ./storybook-static s3://blaze-components-react.thisisblaze.com --delete --acl public-read
